name: Publish Docker image
on:
  push:
    branches: [ master ]
jobs:
  buildAndPush:
    name: Build And Push docker images
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Dovecot
        id: docker_build_dovecot
        uses: docker/build-push-action@v2
        with:
          context: dovecot
          file: dovecot/Dockerfile
          push: true
          tags: erebe/dovecot:latest
      - name: Postfix
        id: docker_build_postfix
        uses: docker/build-push-action@v2
        with:
          context: postfix
          file: postfix/Dockerfile
          push: true
          tags: erebe/postfix:latest
      - name: Dovecot Image digest
        run: echo Dovecot ${{ steps.docker_build_dovecot.outputs.digest }}
      - name: Postfix Image digest
        run: echo Postfix ${{ steps.docker_build_postfix.outputs.digest }}
