name: Publish Postfix Image
on:
  push:
    paths:
    - 'postfix/**'
   
jobs:
  buildAndPush:
    name: Build And Push docker images
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Postfix
        id: docker_build_postfix
        uses: docker/build-push-action@v2
        with:
          context: postfix
          file: postfix/Dockerfile
          push: true
          tags: ghcr.io/erebe/postfix:latest
      - name: Postfix Image digest
        run: echo Postfix ${{ steps.docker_build_postfix.outputs.digest }}
