apiVersion: ENC[AES256_GCM,data:y70=,iv:lNfefOJWCL3qcl5Ir/c/gkCKGqXg/3kEftqNVu87mLU=,tag:08XE0z0MybhG4D+yrinAKg==,type:str]
kind: ENC[AES256_GCM,data:gvI1Vjy5B7Nu,iv:fhpa7sSrPyUnuPGwsZ9yOqSpUoayg68BNlXxidzRTI8=,tag:guJxEMCst91Ww/TQzNBRrg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:q9iJfSsOnZGg,iv:T22dqqWV6yEYsgvBM3myTan6tRHLmcyEBmYeTi6zwuA=,tag:OmGleL1W4V9Tkal1Gzk3hQ==,type:str]
data:
    fetchmailrc: ENC[AES256_GCM,data:5/ROQYoiQALFriXfnU2aDFhCLn2WednX/rNaW+SERkHllqYQGg/v6d+ovu1pX1vje1+2mkIYQqe9WHYKCotOspY9+7qDtdq6s91kAViuFHZsNy5m19PVZP6nnWie5a5Dw1Jubbv4x0wOSWBLKf5Ks0RZIVHgm7CgzOqpP1Ok3Jg9bjvqlsj1kKQBYYDXZBsw8W4x/8Zs/oagvzzb+RQWo3t0XoVGTx2LPuTfvKrXenROeYvh9Y6E5lsiUphcwxqS16c5MBV3oxMW3f+g1CBDjiLUfTL3NdfmztrgfNoeSCGyy3n2d6Den/O+sAblaYGe2lZEwfOb,iv:nrQevlocYIk2QHkB7X/EwA6cxpc/gIWTVJyp7/PnGv0=,tag:vIEkJzr3iQo86/65b0HiWg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2020-10-28T13:15:43Z'
    mac: ENC[AES256_GCM,data:tXQx/aYpklv6xzeaxB0Zm+zFclI+FCvokf0/l0efVHPPegLU4KNa2kL8WGhV40bnfFb4Ghxmq63sX8TY1j7qLxDUQJmgPCDnyQIxhq9CKkYDAzsmuaczmkmCyE0SYbV6FIjY66duE5RXhywXTj/LCRBasqlO3yir1mvp5Tyn7ms=,iv:BpXoH8a+U2a3qxnb76hwj5fNc10NlD9UW6H50TtIyDU=,tag:eFAVHppvAvYUOHtf9mLyfQ==,type:str]
    pgp:
    -   created_at: '2020-10-28T13:13:40Z'
        enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMAzV4V+NXyujFARAAmhMR2VORZlTcH6J9YiNOgrBm2BsooCrwIf3+ph8BeEH3
            4LzLdT5Q2SKwIPfUtuZLxff60n9F6LGb/jkpXk51rn6REgb9e5/s/GOg3VPjVfPE
            kZKTc+4EmSDJGhgx0Jlk5G4e0hUKm+vZwqx/JSCGun5RNFpBVAqAfzYtS8VTH/KW
            Lfi2SaPN8uAuP19UeRis8yyhCrWWWMSsuh2gfud6GJ6Vevl7wAsi/lgion2lDJHf
            fHi7AOuLkWw5aknzzzNnpxDXTRdtj+QVtEMEw+WYd2QQg/y8t4hLjib7AnyA4Vrz
            dbgpM7nk0T7ioGaPr3ltpJ8onHaAp4L+TrBgVq3+p2hLe4+oE4sZyaBfLb9d4IyC
            ltSRRFWdkJMZDrHG0aWRwUQzYS+eb1t8dQeSw2GgAVOWBwxT3HOKc/oBIeZ/o+IP
            vp35T+Du7j3fhouPxyDBQR/WYNIY0X03FFqus22O9/ZlaQWCG6t0bU+eZ9w/PAhO
            KS0J6gaayoB9ii+jwGpRqdWneiuaRc+O5/L7ZrbUqMj3PsxoDjeWytx5rn76G46S
            7RTfusccbPK+T6ShmU11yIPpjhulv3uQM0lO9L9ApFXwsHNW1umxpTQYvVqnfkrr
            uwDWUwf3OC7n66Wb29p2ANNThhB5iSoJCortEUrZuqKTb36SSG+6hIdavAQ5Ps7S
            4AHkOY+3o6ASNsq/flAxWjFheOFJGOA14KDhzCvgoOK8qV7F4NflaIIAb+cWzXDj
            +xxd9yaMy78wEJpqkT/bivQaxXrsUzXgk+RmPvYGvPG9MtfGteAX0pHR4goFO7Xh
            BxQA
            =R85X
            -----END PGP MESSAGE-----
        fp: 2D6D9958A384D88D8F3D1BE8A8F8B1104C38763A
    unencrypted_suffix: _unencrypted
    version: 3.6.1
